Improving the application
w3b3d3v/blockchain-comparison pull request #4
Opened 2023-10-30 18:29 UTC by viniblack

- Create file .env.example
- Improving data visualization from within the table
- Correcting light mode
- Add bootstrap

2023-11-09 20:04 UTC, danicuki requested changes
Great contribution. fix small changes and I can accept this PR.

2023-11-09 20:04 UTC, danicuki commented on pages/_app.js
> -  return <Component {...pageProps} />
we dont use ;

2023-11-09 20:04 UTC, danicuki commented on pages/_document.js
>      </Html>
some here. No ;

2023-11-09 20:04 UTC, danicuki commented on pages/index.js
> +  };
no ;

2023-11-09 20:04 UTC, danicuki commented on styles/Home.module.css
> -  content: '';
why these changes?

2023-11-09 20:04 UTC, danicuki commented on styles/globals.css
> -    'Roboto Mono', 'Oxygen Mono', 'Ubuntu Monospace', 'Source Code Pro',
why this?

2023-11-10 13:01 UTC, viniblack commented on pages/index.js
> +  };
okay

2023-11-10 13:07 UTC, viniblack commented on styles/Home.module.css
> -  content: '';
meu formatador de código estava configurado para usar aspas duplas no lugar das simples. acabei ajustando isso

2023-11-10 13:16 UTC, viniblack reviewed
Adaptation of my code to the project standard

2023-11-10 14:48 UTC, danicuki commented
@viniblack  there are conflicts with the main branch. Please rebase it.

2023-11-10 16:36 UTC, viniblack commented
I think I solved the conflicts by giving git rebase, I'm not sure if it solved all the conflicts, I still have a bit of difficulty with this part of git. 😅

2023-11-10 16:46 UTC, danicuki commented
not yet! It says: "This branch cannot be rebased due to conflicts" 
You have to rebase your repo with the

2023-11-10 16:48 UTC, danicuki commented
You have duplicated commits on these PR. I don't know exactly what did you do. You have to make a clean PR from the last version of the main repo only with new stuff

2023-11-10 16:49 UTC, danicuki commented
My recommendation, if you can't make it only using git is to create a fresh new fork of the main repo, change the supposed files and make a single commit with all modifications

2023-11-11 18:54 UTC, closed without merging